---
 - name: "variables"
   hosts: localhost
   vars:
    - username: Ansible
    - home: /home/osboxes/ansibledemo/variable.yaml
   tasks:
    - name: print variable
      debug:
       msg: "Username : {{username}}, Home path : {{home}}"
